[package]
name = "bj6_rng"
version = "0.0.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_auto_plugin = { workspace = true }
bevy_rand = { workspace = true }
bevy_prng = { workspace = true }
rand_core = { workspace = true }


[features]
wasm = [
    "bevy_rand/wasm_js"
]
